name: Emscripten

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  js-build:
    name: Build liblouis for js

    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969 # v2.4.0
      with:
        egress-policy: audit

    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

    - name: Obtain liblouis-js
      run: git clone https://github.com/liblouis/liblouis-js.git

    - name: Pull the docker image
      run: docker pull dolp/liblouis-js-build-travis:1.37.3-64bit

    - name: Run the docker image
      run: docker run --rm -v $(pwd):/src dolp/liblouis-js-build-travis:1.37.3-64bit /bin/bash  ".github/workflows/scripts/emscripten-build.sh"

    - name: Upload the Table assets
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: build-tables-embeded-root-utf32.js
        path: ./out/build-tables-embeded-root-utf32.js